---
# tasks file for underlay

- name: TASK 1 - ENABLE FEATURES
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: [ospf, pim]

- name: TASK 2 - CONFIGURE AND ENABLE ETHERNET AND LOOPBACK INTERFACES
  cisco.nxos.nxos_interfaces:
    config: "{{ interfaces_config[inventory_hostname] }}"
    state: merged

- name: TASK 3 - L3 CONFIGURATION OF LOOPBACK INTERFACES
  cisco.nxos.nxos_l3_interfaces:
    config: "{{ loopback_l3_interfaces[inventory_hostname] }}"
    state: merged

- name: TASK 4 - IP UNNUMBERED ETHERNET INTERFACES
  cisco.nxos.nxos_config:
    lines:
      - medium p2p
      - ip unnumbered loopback0
    parents: interface {{ item }}
  loop: "{{ physical_interfaces_list[inventory_hostname] }}"

- name: TASK 5 - CONFIGURE OSPF PROCESS
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
      - process_id: UNDERLAY
        router_id: "{{ ospf_routerid[inventory_hostname]['routerid'] }}"
        areas:
        - area_id: 0.0.0.0
          authentication:
            message_digest: yes
            # set: yes
    state: merged

- name: TASK 6 - CONFIGURE INTERFACES WITH OSPF
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ item }}"
        address_family:
        - afi: ipv4
          message_digest_key:
            encryption: 0
            key: "{{ ospf_md5_key }}"
            key_id: "{{ ospf_md5_keyid }}"
          network: point-to-point
          processes:
          - area:
              area_id: 0.0.0.0
              secondaries: no
    state: merged
  loop: "{{ interfaces_list[inventory_hostname] }}"

- name: TASK 7 - ENABLE PIM SPARSE MODE ON INTERFACES
  cisco.nxos.nxos_pim_interface:
    interface: "{{ item }}"
    sparse: yes
    state: present
  loop: "{{ interfaces_list[inventory_hostname] }}"

- name: TASK 8 - CONFIGURE PIM RP ADDRESS
  cisco.nxos.nxos_pim_rp_address:
    rp_address: "{{ rp_address }}"
    state: present

- name: TASK 9 - CONFIGURE SPINES WITH PIM ANYCAST RPS
  cisco.nxos.nxos_config:
    lines:
      - ip pim anycast-rp {{ rp_address }} {{ item }}
  loop: "{{ anycast_rps }}"
  when: "'spines' in group_names"
...