---
- name: single task
  hosts: all
  gather_facts: no
  vars_files:
    - vpc_phys_vars.yml
    - topology_vars.yml
    - tenant_vars.yml

  tasks:
  - name: TASK 10 - ASSOCIATE L3 VNI TO VRF IN THE VTEP INTERFACE
    cisco.nxos.nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item['vni'] }}"
      assoc_vrf: "{{ item['assoc_vrf'] }}"
    loop: "{{ assoc_vrf[inventory_hostname] }}"
    when: "inventory_hostname in assoc_vrf"
    register: output

  - name: OUTPUT
    debug:
      # msg: "{{ output }}"
      # msg: "{{ output['commands'] }}"
      msg: "{{ item['commands'] }}"
    loop: "{{ output['results'] }}"
    # when: "'leafs' in group_names"
    when: "inventory_hostname in assoc_vrf"
...