---
- name: single task
  hosts: all
  gather_facts: no
  vars_files:
    - vpc_phys_vars.yml
    - topology_vars.yml
    - tenant_vars.yml

  tasks:
  # - name: TASK 6/9 - CONFIGURE INTERFACES WITH OSPF
  #   cisco.nxos.nxos_ospf_interfaces:
  #     config:
  #     - name: "{{ item }}"
  #       address_family:
  #       - afi: ipv4
  #         processes:
  #         - process_id: UNDERLAY
  #           area:
  #             area_id: 0.0.0.0
  #         message_digest_key:
  #           encryption: 0
  #           key: "{{ ospf_md5_key }}"
  #           key_id: "{{ ospf_md5_keyid }}"
  #         network: point-to-point
  #     state: merged
  #   loop: "{{ interfaces_list[inventory_hostname] }}"
    # register: output

  - name: TASK 6/9 - CONFIGURE INTERFACES WITH OSPF
    cisco.nxos.nxos_config:
      lines:
      - ip router ospf UNDERLAY area 0.0.0.0
      parents: interface {{ item }}
    loop: "{{ interfaces_list[inventory_hostname] }}"
    register: output

  - name: OUTPUT
    debug:
      # msg: "{{ output }}"
      # msg: "{{ output['commands'] }}"
      msg: "{{ item['commands'] }}"
    loop: "{{ output['results'] }}"
    # when: "'leafs' in group_names"
    # when: "inventory_hostname in assoc_vrf"
...