---
- name: single task
  hosts: all
  gather_facts: no
  vars_files:
    - topology_vars.yml
    - tenant_vars.yml

  tasks:
  - name: test
    cisco.nxos.nxos_vrf_interface:
      interface: "{{ item['name'] }}"
      vrf: "{{ item['vrf'] }}"
    loop: "{{ core_facing_svi_vrf[inventory_hostname] }}"
    when: "inventory_hostname in core_facing_svi_vrf"
    register: output

  - name: OUTPUT
    debug:
      # msg: "{{ output }}"
      # msg: "{{ output['commands'] }}"
      msg: "{{ item['commands'] }}"
    loop: "{{ output['results'] }}"
    # when: "'leafs' in group_names"
    # when: "inventory_hostname in leafs"
    when: "inventory_hostname in core_facing_svi_vrf"
...