---
- name: single task
  hosts: all
  gather_facts: no
  vars_files:
    - topology.yml

  tasks:
  - name: TASK 9 - ADD L2VPN AFI TO ROUTE REFLECTORS
    cisco.nxos.nxos_bgp_neighbor_af:
      afi: l2vpn
      asn: "{{ bgp_asn }}"
      neighbor: "{{ item }}"
      route_reflector_client: yes
      safi: evpn
      send_community: both
    loop: "{{ rr_bgp_neighbours }}"
    when: "'rr' in group_names"
    register: output

  - name: OUTPUT
    debug:
      # msg: "{{ output }}"
      # msg: "{{ output['commands'] }}"
      msg: "{{ item['commands'] }}"
    loop: "{{ output['results'] }}"
    when: "'rr' in group_names"
...