---
- name: single task
  hosts: all
  gather_facts: no
  vars_files:
    - topology_vars.yml
    - tenant_vars.yml

  tasks:
  - name: test
    cisco.nxos.nxos_l3_interfaces:
      config: "{{ svi_l3[inventory_hostname] }}"
    when: "inventory_hostname in svi_l3"
    register: output

  - name: OUTPUT
    debug:
      # msg: "{{ output }}"
      msg: "{{ output['commands'] }}"
      # msg: "{{ item['commands'] }}"
    # loop: "{{ output['results'] }}"
    # when: "'leafs' in group_names"
    # when: "inventory_hostname in leafs"
    when: "inventory_hostname in svi_l3"
...