---
- name: single task
  hosts: all
  gather_facts: no
  vars_files:
    - topology_vars.yml
    - tenant_vars.yml

  tasks:
  - name: test
    cisco.nxos.nxos_bgp_global:
      config: "{{ bgp_global[inventory_hostname] }}"
    when: "inventory_hostname in bgp_global"
    register: output

  - name: OUTPUT
    debug:
      # msg: "{{ output }}"
      msg: "{{ output['commands'] }}"
      # msg: "{{ item['commands'] }}"
    # loop: "{{ output['results'] }}"
    # when: "'leafs' in group_names"
    when: "inventory_hostname in bgp_global"
...