---
- name: single task
  hosts: all
  gather_facts: no
  vars_files:
    - topology_vars.yml
    - tenant_vars.yml

  tasks:
  - name: TASK 7 - CREATE SVI INTERFACES
    cisco.nxos.nxos_interfaces:
      config: "{{ svi_interfaces[inventory_hostname] }}"
    when: "inventory_hostname in svi_interfaces"
    register: output

  - name: OUTPUT
    debug:
      # msg: "{{ output }}"
      msg: "{{ output['commands'] }}"
      # msg: "{{ item['commands'] }}"
    # loop: "{{ output['results'] }}"
    # when: "'leafs' in group_names"
    when: "inventory_hostname in svi_interfaces"
...