---
- name: vxlan_vtep
  hosts: all
  gather_facts: no
  tasks:
  - name: TASK 6 - CONFIGURE NVE INTERFACE ON LEAFS
    cisco.nxos.nxos_vxlan_vtep:
      interface: nve1
      # global_ingress_replication_bgp: no
      global_mcast_group_L2: default
      global_mcast_group_L3: default
      global_suppress_arp: yes
      host_reachability: yes
      shutdown: no
      source_interface: Loopback1
      state: present
    when: "'leafs' in group_names"
...