---
# tasks file for overlay

- name: TASK 1 - ENABLE FEATURES ON ROUTE REFLECTORS
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: [bgp, "nv overlay"]
  when: "'rr' in group_names"

- name: TASK 2 - ENABLE FEATURES ON LEAFS
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: [bgp, "nv overlay", interface-vlan, vn-segment-vlan-based]
  when: "'leafs' in group_names"

- name: TASK 3 - ENABLE EVPN CONTROL PLANE ON ROUTE REFLECTORS AND LEAFS
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: yes
  when: ('rr' in group_names) or ('leafs' in group_names)

- name: TASK 4 - CONFIGURE ANYCAST GATEWAY MAC ON LEAFS
  cisco.nxos.nxos_overlay_global:
    anycast_gateway_mac: "{{ anycast_gateway_mac }}"
  when: "'leafs' in group_names"

- name: TASK 5 - CREATE NVE INTERFACE ON LEAFS
  cisco.nxos.nxos_interfaces:
    config:
    - name: nve1
      description: VIRTUAL TUNNEL ENDPOINT (VTEP)
      enabled: true
  when: "'leafs' in group_names"

- name: TASK 6 - CONFIGURE NVE INTERFACE ON LEAFS
  cisco.nxos.nxos_vxlan_vtep:
    interface: nve1
    global_mcast_group_L2: "{{ global_l2_mcast_group }}"
    global_suppress_arp: yes
    host_reachability: yes
    shutdown: no
    source_interface: Loopback1
  when: "'leafs' in group_names"

- name: TASK 7 - CONFIGURE BGP ON ROUTE REFLECTORS AND LEAFS
  cisco.nxos.nxos_bgp:
    asn: "{{ bgp_asn }}"
    log_neighbor_changes: yes
    router_id: "{{ routerid[inventory_hostname]['rid'] }}"
    shutdown: no
  when: ('rr' in group_names) or ('leafs' in group_names)

- name: TASK 8 - ADD BGP NEIGHBOURS TO ROUTE REFLECTORS
  cisco.nxos.nxos_bgp_neighbor:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item }}"
    remote_as: "{{ bgp_asn }}"
    update_source: loopback1
  loop: "{{ rr_bgp_neighbours }}"
  when: "'rr' in group_names"

- name: TASK 9 - ADD L2VPN AFI TO ROUTE REFLECTORS
  cisco.nxos.nxos_bgp_neighbor_af:
    afi: l2vpn
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item }}"
    route_reflector_client: yes
    safi: evpn
    send_community: both
  loop: "{{ rr_bgp_neighbours }}"
  when: "'rr' in group_names"

- name: TASK 10 - ADD BGP NEIGHBOURS TO LEAFS
  cisco.nxos.nxos_bgp_neighbor:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item }}"
    remote_as: "{{ bgp_asn }}"
    update_source: loopback1
  loop: "{{ leaf_bgp_neighbours }}"
  when: "'leafs' in group_names"

- name: TASK 11 - ADD L2VPN AFI TO LEAFS
  cisco.nxos.nxos_bgp_neighbor_af:
    afi: l2vpn
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item }}"
    safi: evpn
    send_community: both
  loop: "{{ leaf_bgp_neighbours }}"
  when: "'leafs' in group_names"
...